MB9WebCore/MB9WebTemplate/Areas/AdminCMS/Controllers/DocumentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MB9.CMS.Web.Areas.AdminCMS.Models;
using Newtonsoft.Json;
using MB9.CMS.Web.Helper;
using System.Web.Configuration;
using MB9.Core.Web.Services;
using MB9.Core.Web.Controllers;
using MB9.Core.Web.Filter;
using MB9.CMS.Core.Services;
using MB9.CMS.Core.CMS.Model;
using MB9.CMS.Core.EMS.Model;
using Microsoft.Practices.Unity;
using MB9.Core.Service;

namespace MB9.CMS.Web.Areas.AdminCMS.Controllers
{
    //[UserAuthorizeFilterAttribute(role = "AdminPage")]
    public class DocumentController : BaseSecureController
    {
        private readonly ICmsService _cmsService;
        private readonly IEmsService _emsService;
        CrudFunctions crFuncs;

        public DocumentController(ICmsService cmsService, IEmsService emsService)
        {
            this._cmsService = cmsService;
            this._emsService = emsService;
            crFuncs = new CrudFunctions(_cmsService , _emsService);
        }

        public ActionResult Index() 
        {
            var documentDef = _cmsService.GetAllDocDefs().Where(x => x.Visibility.Equals(true));
            var pages = _cmsService.GetAllPages().Where(m => m.PageCategory != null);
            var langs = _cmsService.GetAllLangs();

            DocIndexViewModel model = new DocIndexViewModel();
            
            model.allLangs = CrudFunctions.LanguageDropdown(langs);

            model.allDocs = from m in documentDef
                            select new SelectListItem() { Text = m.Name, Value = m.DocType };

            model.allPages = pages;
            
            return View(model);
        }

        public ActionResult Blog()
        {
            var documentDef = _cmsService.GetAllDocDefs().Where(x => x.Visibility.Equals(true));
            var pages = _cmsService.GetAllPages().Where(m => m.PageCategory.Equals("blog"));
            var langs = _cmsService.GetAllLangs();

            DocIndexViewModel model = new DocIndexViewModel();

            model.allLangs = CrudFunctions.LanguageDropdown(langs);

            model.allDocs = from m in documentDef
                            select new SelectListItem() { Text = m.Name, Value = m.DocType };

            model.allPages = pages;

            return View(model);
        }

        public ActionResult Newsletter()
        {
            var documentDef = _cmsService.GetAllDocDefs().Where(x => x.Visibility.Equals(true));
            var pages = _cmsService.GetAllPages().Where(m => m.PageCategory.Equals("newsletter"));
            var langs = _cmsService.GetAllLangs();

            DocIndexViewModel model = new DocIndexViewModel();

            model.allLangs = CrudFunctions.LanguageDropdown(langs);

            model.allDocs = from m in documentDef
                            select new SelectListItem() { Text = m.Name, Value = m.DocType };

            model.allPages = pages;

            return View(model);
        }

        public ActionResult Create(String doctype, String pageCategory,  String lang = null)
        {
            DocDefinition docDef;
            DocPart doc;
            DocPartContent docContent;
            PageMap pageDetails;
            Event events;

            crFuncs.createUtils(doctype, pageCategory, lang, out docDef, out doc, out docContent, out pageDetails, out events);

            return ShowPage(pageDetails, doc, docDef, docContent);

        }

        [HttpGet]
        public ActionResult EditPage(int id, String lang = null)
        {
            //Event events;

            PageMap pageEvents;
            DocPart docpart;
            DocDefinition docDef;
            DocPartContent docPartContent;

            pageEvents = _cmsService.GetPage(id);

            crFuncs.editGetUtils(id, lang, pageEvents, out docpart, out docDef, out docPartContent);

            return ShowPage(pageEvents, docpart, docDef, docPartContent);

        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult EditPage(FormCollection collection)
        {
            int pageDataID = -1;
            int.TryParse(collection["PageMapID"], out pageDataID);
            var page = new PageMap();
            DocPart docPart = null;
            DocPartContent docPartContent = null;
            DocDefinition docDef = null;

            if (pageDataID > 0)
            {
                page = _cmsService.GetPage(pageDataID);

            }
            else
            {
                page = new PageMap();
            }

            if (page != null)
            {
                page.Title = collection["PageName"] ?? "defaultPage" + page.DocPartId;
                page.SeoName = collection["PageUrl"] ?? "defaultUrl" + page.DocPartId;
                page.ViewTemplate = collection["PageViewTemplate"] ?? "defaultViewTemplate";
                page.PageCategory = collection["PageCategory"] ?? null;

                if (collection["PageActiveCheckbox"].Contains("true"))
                {
                    page.Active = true;
                }
                else
                {
                    page.Active = false;
                }

                //crFuncs.LoadUpdateDocPart(collection, out docPart, out docPartContent, out docDef);

                var formCollectionVals = crFuncs.GetDocPartVals(collection);
                String lang = collection["lang"] ?? WebConfigurationManager.AppSettings["DefaultLanguage"];

                docPart = _cmsService.SetUpDocPart(formCollectionVals, lang);
                docPartContent = _cmsService.SetUpDocPartContent(formCollectionVals, lang);
                
                var docType = formCollectionVals.DocType;
                docDef = _cmsService.GetDocDef(docType);

                Dictionary<string, string> currentEntry = null;
                if (docPartContent.Content != null)
                {
                    currentEntry = JsonConvert.DeserializeObject<Dictionary<string, string>>(docPartContent.Content);
                }

                docPartContent.Content = JsonConvert.SerializeObject(CrudFunctions.MergeContent(collection, currentEntry));
                

                _cmsService.SavePage(page, docPart, docPartContent);
            }

            return ShowPage(page, docPart, docDef, docPartContent);
        }

        [NonAction]
        private ActionResult ShowPage(PageMap page, DocPart doc, DocDefinition docDef, DocPartContent docContent)
        {
            if (page == null || doc == null || docDef == null || docContent == null)
            {
                // return error;
            }

            var langs = _cmsService.GetAllLangs();
            var langList = CrudFunctions.LanguageDropdown(langs);

            var model = new PageViewModel(page, docDef, doc, docContent, langList);
            ViewBag.DocModel = model;

            return View("EditPage", model);
        }

        //DocPart
        public ActionResult CreateDocPart(String doctype, String lang = null, int pid = -1, string pmemeber = null)
        {
            DocDefinition docDef;
            DocPart doc;
            DocPartContent docContent;
            crFuncs.createDocPartUtils(doctype, lang, pid, pmemeber, out docDef, out doc, out docContent);

            return ShowDocPart(doc, docDef, docContent);
        }

        
        [HttpGet]
        public ActionResult EditDocPart(int id, String lang = null)
        {
            DocPart doc;
            DocDefinition docDef;
            DocPartContent docPartContent;
            crFuncs.editDocPartUtils(id, lang, out doc, out docDef, out docPartContent);

            return ShowDocPart(doc, docDef, docPartContent);

        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult EditDocPart(FormCollection collection) 
        {
            DocPart docPart = null;
            DocPartContent docPartContent = null;
            DocDefinition docDef = null;
            
            //crFuncs.LoadUpdateDocPart(collection, out docPart, out docPartContent, out docDef);

            var formCollectionVals = crFuncs.GetDocPartVals(collection);
            String lang = collection["lang"] ?? WebConfigurationManager.AppSettings["DefaultLanguage"];

            docPart = _cmsService.SetUpDocPart(formCollectionVals, lang);
            docPartContent = _cmsService.SetUpDocPartContent(formCollectionVals, lang);
            var docType = formCollectionVals.DocType;
            docDef = _cmsService.GetDocDef(docType);

            Dictionary<string, string> currentEntry = null;
            if (docPartContent.Content != null)
            {
                currentEntry = JsonConvert.DeserializeObject<Dictionary<string, string>>(docPartContent.Content);
            }

            docPartContent.Content = JsonConvert.SerializeObject(CrudFunctions.MergeContent(collection, currentEntry));
                
            if (docPart != null)
            {
                _cmsService.SaveDocPart(docPart, docPartContent);
            }

            return ShowDocPart(docPart, docDef, docPartContent);
        }

        [NonAction]
        private ActionResult ShowDocPart(DocPart doc, DocDefinition docDef, DocPartContent docContent)
        {
            if (doc == null || docDef == null || docContent == null)
            {
                // return error;
            }

            var langs = _cmsService.GetAllLangs();
            var langList = CrudFunctions.LanguageDropdown(langs);

            var model = new DocPartViewModel(docDef, doc, docContent, langList);

            ViewBag.DocModel = model;

            return View("EditDocPart", model);
        }

        //Docpart "List" items
        [HttpGet]
        public ActionResult ListItems(int parentId, string parentprop, string lang) 
        {
            if (parentprop != null && parentId > 0) 
            {

MB9WebCore/MB9WebTemplate/Controllers/PageViewController.cs
using MB9.CMS.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Configuration;
using System.Web.Mvc;
using MB9.Core.Web.Services;
using MB9.CMS.Core.Services;
using MB9.CMS.Core.CMS.Model;
using MB9.CMS.Core.EMS.Model;
using MB9.CMS.Core.CMS.ViewModel;
using System.Web.Caching;

namespace MB9.CMS.Web.Controllers
{
    public class PageViewController : Controller
    {
        private readonly ICmsService _cmsService;
        private readonly IEmsService _emsService;
        private readonly IMenuService _menuService;

        public PageViewController(ICmsService cmsService, IEmsService emsService, IMenuService menuService)
        {
            this._cmsService = cmsService;
            this._emsService = emsService;
            this._menuService = menuService;
        }

        //
        // GET: /PageView/

        public ActionResult Index(string url, string lang = null)
        {
            lang = lang ?? WebConfigurationManager.AppSettings["DefaultLanguage"];

            var page = _cmsService.GetAllPages().FirstOrDefault(x => x.SeoName == url);

            var docpart = _cmsService.GetDocParts().FirstOrDefault(x => x.ID == page.DocPartId);
            var doccontent = _cmsService.GetDocPartContents().FirstOrDefault(x => x.DocPartId.Equals(docpart.ID) && x.Language.Equals(lang));

            List<int> listContent = _cmsService.GetDocParts().Where(x => x.ParentId.Equals(page.DocPartId)).Select(x => x.ID).ToList();
            var recordList = new List<DocPartContent>();

            if (listContent.Count > 0)
            {
                foreach (var itemId in listContent)
                {
                    var item = _cmsService.GetDocPartContents().OrderBy(x => x.Language != lang).FirstOrDefault(x => x.DocPartId.Equals(itemId));
                    recordList.Add(item);
                }

                ViewBag.ListData = recordList;
            }

            Event events = null;

            var model = new TemlatePreviewViewModel(docpart, doccontent, page, events);

            return View(model);
        }

        public ActionResult EventPreview(string url, string lang = null) 
        {
            lang = lang ?? WebConfigurationManager.AppSettings["DefaultLanguage"];

            var events = _emsService.GetAllEvents().FirstOrDefault(x => x.SeoName == url);
            var docpart = _cmsService.GetDocParts().FirstOrDefault(x => x.ID == events.DocPartId);
            var doccontent = _cmsService.GetDocPartContents().FirstOrDefault(x => x.DocPartId.Equals(docpart.ID) && x.Language.Equals(lang));

            PageMap page = null;

            var model = new TemlatePreviewViewModel(docpart, doccontent, page, events);

            return View(model);
        }

        public ActionResult DisplayMenuBar(string language = "ENG")
        {
            MenuView menu_tree = HttpRuntime.Cache.Get(language + "_menu") as MenuView;
            if (menu_tree == null)
            {
                menu_tree = _menuService.GetMenuAsTree(language,"display");

                HttpRuntime.Cache.Insert(language + "_menu", menu_tree, null, DateTime.UtcNow.AddHours(1), Cache.NoSlidingExpiration);

            }
            return PartialView("_displayMenu",menu_tree);
        }



    }
}

MB9WebCore/MB9WebTemplate/Areas/AdminCMS/Views/Document/Blog.cshtml
@model  MB9.CMS.Web.Areas.AdminCMS.Models.DocIndexViewModel

@{

    ViewBag.Title = "Blogs";
    ViewBag.Header = "Blog List";
    var count = 1;
}

<div class="form-group">

    <div class="col-sm-9" style="width:100%">
        <div class="container-fluid">

            <!--Language selector-->
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title"> Create Blog </h3>
                </div>
                <div class="panel-body">
                    @Html.DropDownList("LangSelect", Model.allLangs, new { @class = "dropdown btn btn-default btn-sm" })

                    <div id="CreateBlog" class="btn btn-primary btn-sm">Create</div>

                    <div id="NullWarning" class="panel panel-danger" style="display: none; margin-top: 10px;">
                        <div class=" panel-heading">
                            Please Select the Language
                        </div>
                    </div>
                </div>
            </div>

            <!-- DataTable -->
            <div class="panel panel-default">
                <div class="panel-heading">
                    Blogs
                </div>
                <div class="panel-body">
                    <table id="dataTable_Pages" class="table table-striped table-hover display compact">
                        <thead>
                            <tr>
                                <th class="col-sm-1">Sl.No</th>
                                <th class="col-sm-3">Blog Name</th>
                                <th class="col-sm-3">URL</th>
                                <th class="col-sm-2">Active</th>
                                <th class="col-sm-2">Edit</th>
                                <th colspan="2" class="col-sm-1">Preview</th>

                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model.allPages)
                            {

                                <tr>
                                    <td>@count</td>
                                    <td>@item.Title</td>
                                    <td>@item.SeoName</td>
                                    <td>
                                        @if (item.Active)
                                        {
                                            @Html.Label(" ", new { @class = "glyphicon glyphicon-ok", style = "padding-left: 10%;" })
                                        }
                                        else
                                        {
                                            @Html.Label(" ", new { @class = "glyphicon glyphicon-remove", style = "padding-left: 10%;" })
                                        }
                                    </td>
                                    <td>
                                        <div class="btn-group btn-group-xs">
                                            @Html.ActionLink("ENG", "EditPage", new { @id = item.ID, lang = "EN" }, new { @class = "btn btn-default btn-xs" })
                                            @Html.ActionLink("CHN", "EditPage", new { @id = item.ID, lang = "ZH" }, new { @class = "btn btn-default btn-xs" })
                                        </div>
                                    </td>
                                    <td>
                                        <a class="glyphicon glyphicon-expand" href="@Url.Action("Index", "PageView", new { area ="", lang = "EN", url = item.SeoName})" target="_blank"></a>
                                    </td>
                                    <td>
                                        <a class="glyphicon glyphicon-expand" href="@Url.Action("Index", "PageView", new { area ="", lang = "ZH", url = item.SeoName})" target="_blank"></a>
                                    </td>
                                </tr>

                                        count++;
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
<script>

    $(document).ready(function () {

        $('a.mainmenu').removeClass("active");
        $('#menu_pages').addClass("active");
        $('#menu_blog').addClass("active");

        $('#dataTable_Pages').dataTable(
            {
                "ordering": false,
                "paging": true,
                "pagingType": "full_numbers",
                "stateSave": true
            });
    });

    $('#CreateBlog').click(function () {

        var selectedLang = $('#LangSelect').val();


        if (selectedLang != "") {
            $('#NullWarning').hide();
            location.href = '@(Url.Action("Create", "Document"))?doctype=blog&pageCategory=blog&lang=' + selectedLang;
        }
        else {
            $('#NullWarning').show();
        }

    });

</script>

MB9WebCore/MB9WebTemplate/Areas/AdminCMS/Views/Document/EditPage.cshtml
@model  MB9.CMS.Web.Areas.AdminCMS.Models.PageViewModel
@{
    ViewBag.Title = "Dashboard";
    ViewBag.Header = "Edit Page :";
    ViewBag.Subheading = Model.Def.Name + Model.Language;
}

<div class="container" style="width:100%">
    <div>
        <a href="@VirtualPathUtility.ToAbsolute("~/AdminCMS/Document/Index")" class="btn btn-primary btn-xs" style="float:left"> Back </a>
        <br />
        <br />
        <br />
    </div>

    <div class="row">

        @using (Html.BeginForm("EditPage", "Document", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
        {
            @Html.Partial("EditPagePartial", Model)

            <br />
            <a class="glyphicon glyphicon-expand" href="@Url.Action("Index", "PageView", new { area ="", lang = Model.Language, url = Model.Page.SeoName})" target="_blank"> Preview</a>
            <hr />
            <br />
            @Html.Partial("EditDocPartPartial", Model)
            <br />
            <br />
            <hr />
            <button type="submit" class="btn col-sm-2" >Save</button>
            
        }

    </div>
    <br />
    <br />

</div>

MB9WebCore/MB9WebTemplate/Areas/AdminCMS/Views/Document/EditPagePartial.cshtml
@model  MB9.CMS.Web.Areas.AdminCMS.Models.PageViewModel

<div>
    <div class="row">
        @Html.Hidden("docPartID_Page", Model.Page.DocPartId)
        @Html.Hidden("PageMapID", Model.Page.ID)
        @Html.Hidden("PageCategory", Model.Page.PageCategory)
    </div>

    <div class="form-horizontal" role="form">
        <div class="well">
            <div class="form-group">
                @Html.Label("Page Active Flag", new { @class = "col-sm-2 control-label", style = "text-align:center" })
                <div class="col-sm-10">
                    @Html.CheckBox("PageActiveCheckbox", Model.Page.Active)
                </div>
            </div>

            <div class="form-group">
                @Html.Label("Page Name", new { @class = "col-sm-2 control-label", style = "text-align:center" })
                <div class="col-sm-2">
                    @Html.TextBox("PageName", Model.Page.Title, new { @class = "form-control" })
                </div>
            
                @Html.Label("Page URL", new { @class = "col-sm-2 control-label", style = "text-align:center" })
                <div class="col-sm-2">
                    @Html.TextBox("PageURL", Model.Page.SeoName, new { @class = "form-control" })
                </div>
            
                @Html.Label("View Template", new { @class = "col-sm-2 control-label", style = "text-align:center" })
                <div class="col-sm-2">
                    <input class="form-control" type="text" placeholder="@Model.Page.ViewTemplate" readonly>
                </div>
            </div>
        </div>
    </div>
</div>

MB9WebCore/MB9WebTemplate/Areas/AdminCMS/Views/Document/Index.cshtml
@model  MB9.CMS.Web.Areas.AdminCMS.Models.DocIndexViewModel

@*@{
    
    ViewBag.Title = "Pages";
    ViewBag.Header = "Page List";
    var count = 1;
}*@

@*<div class="form-group">

    <div class="col-sm-9" style="width:100%">
        <div class="container-fluid">

            <!--Page Create Template and Language selector-->
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title"> Create Page </h3>
                </div>
                <div class="panel-body">
                    @Html.DropDownList("DocTypeSelect", Model.allDocs, "Select Template", new { @class = "dropdown btn btn-default btn-sm" })

                    @Html.DropDownList("LangSelect", Model.allLangs, "Select Language", new { @class = "dropdown btn btn-default btn-sm" })

                    <div id="CreatePage" class="btn btn-primary btn-sm">Create</div>
                    
                    <div id="NullWarning" class="panel panel-danger" style="display: none; margin-top: 10px;">
                        <div class=" panel-heading">
                            Please Select the Document Type and Language
                    </div>
                    </div>
                </div>
            </div>

            <!-- DataTable -->
            <div class="panel panel-default">
                <div class="panel-heading">
                    Pages
                </div>
                <div class="panel-body">
                    <table id="dataTable_Pages" class="table table-striped table-hover display compact">
                        <thead>
                            <tr>
                                <th class="col-sm-1">Sl.No</th>
                                <th class="col-sm-3">Page Name</th>
                                <th class="col-sm-3">URL</th>
                                <th class="col-sm-2">Active</th>
                                <th class="col-sm-2">Edit</th>
                                <th colspan="2" class="col-sm-1">Preview</th>

                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model.allPages)
                            {

                                <tr>
                                    <td>@count</td>
                                    <td>@item.Title</td>
                                    <td>@item.SeoName</td>
                                    <td>
                                        @if (item.Active)
                                        {
                                            @Html.Label(" ", new { @class = "glyphicon glyphicon-ok", style = "padding-left: 10%;" })
                                        }
                                        else 
                                        {
                                            @Html.Label(" ", new { @class = "glyphicon glyphicon-remove", style = "padding-left: 10%;" })
                                        }
                                    </td>
                                    <td>
                                        <div class="btn-group btn-group-xs">
                                            @Html.ActionLink("ENG", "EditPage", new { @id = item.ID, lang = "EN" }, new { @class = "btn btn-default btn-xs" })
                                            @Html.ActionLink("CHN", "EditPage", new { @id = item.ID, lang = "ZH" }, new { @class = "btn btn-default btn-xs" })
                                        </div>
                                    </td>
                                    <td>
                                        <a class="glyphicon glyphicon-expand" href="@Url.Action("Index", "PageView", new { area ="", lang = "EN", url = item.SeoName})" target="_blank"></a>
                                    </td>
                                    <td>
                                        <a class="glyphicon glyphicon-expand" href="@Url.Action("Index", "PageView", new { area ="", lang = "ZH", url = item.SeoName})" target="_blank"></a>
                                    </td>
                                </tr>

                                count++;
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
<script>

    $(document).ready(function () {

        $('a.mainmenu').removeClass("active");
        $('#menu_pages').addClass("active");
        $('#menu_allpages').addClass("active");

        $('#dataTable_Pages').dataTable(
            {
                "ordering": false,
                "paging": true,
                "pagingType": "full_numbers",
                "stateSave": true
            });
    });

    $('#CreatePage').click(function () {

        var selectedType = $('#DocTypeSelect').val();
        var selectedLang = $('#LangSelect').val();
        

        if (selectedType != "" || selectedLang != "") {
            $('#NullWarning').hide();
            location.href = '@(Url.Action("Create", "Document"))?doctype='+selectedType+'&pageCategory=page&lang='+selectedLang;
        }
        else {
            $('#NullWarning').show();
        }

    });*@

</script>

MB9WebCore/MB9WebTemplate/Areas/AdminCMS/Views/Document/Newsletter.cshtml
@model  MB9.CMS.Web.Areas.AdminCMS.Models.DocIndexViewModel

@{

    ViewBag.Title = "Newsletter";
    ViewBag.Header = "Newsletter List";
    var count = 1;
}

<div class="form-group">

    <div class="col-sm-9" style="width:100%">
        <div class="container-fluid">

            <!--Language selector-->
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title"> Create Newsletter </h3>
                </div>
                <div class="panel-body">
                     @Html.DropDownList("LangSelect", Model.allLangs, new { @class = "dropdown btn btn-default btn-sm" })

                    <div id="CreateNewsletter" class="btn btn-primary btn-sm">Create</div>

                    <div id="NullWarning" class="panel panel-danger" style="display: none; margin-top: 10px;">
                        <div class=" panel-heading">
                            Please Select the Language
                        </div>
                    </div>
                </div>
            </div>

            <!-- DataTable -->
            <div class="panel panel-default">
                <div class="panel-heading">
                    Newsletter
                </div>
                <div class="panel-body">
                    <table id="dataTable_Pages" class="table table-striped table-hover display compact">
                        <thead>
                            <tr>
                                <th class="col-sm-1">Sl.No</th>
                                <th class="col-sm-3">Newsletter Name</th>
                                <th class="col-sm-3">URL</th>
                                <th class="col-sm-2">Active</th>
                                <th class="col-sm-2">Edit</th>
                                <th colspan="2" class="col-sm-1">Preview</th>

                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model.allPages)
                            {

                                <tr>
                                    <td>@count</td>
                                    <td>@item.Title</td>
                                    <td>@item.SeoName</td>
                                    <td>
                                        @if (item.Active)
                                        {
                                            @Html.Label(" ", new { @class = "glyphicon glyphicon-ok", style = "padding-left: 10%;" })
                                        }
                                        else
                                        {
                                            @Html.Label(" ", new { @class = "glyphicon glyphicon-remove", style = "padding-left: 10%;" })
                                        }
                                    </td>
                                    <td>
                                        <div class="btn-group btn-group-xs">
                                            @Html.ActionLink("ENG", "EditPage", new { @id = item.ID, lang = "EN" }, new { @class = "btn btn-default btn-xs" })
                                            @Html.ActionLink("CHN", "EditPage", new { @id = item.ID, lang = "ZH" }, new { @class = "btn btn-default btn-xs" })
                                        </div>
                                    </td>
                                    <td>
                                        <a class="glyphicon glyphicon-expand" href="@Url.Action("Index", "PageView", new { area ="", lang = "EN", url = item.SeoName})" target="_blank"></a>
                                    </td>
                                    <td>
                                        <a class="glyphicon glyphicon-expand" href="@Url.Action("Index", "PageView", new { area ="", lang = "ZH", url = item.SeoName})" target="_blank"></a>
                                    </td>
                                </tr>

                                        count++;
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
<script>

    $(document).ready(function () {

        $('a.mainmenu').removeClass("active");
        $('#menu_pages').addClass("active");
        $('#menu_newsletter').addClass("active");

        $('#dataTable_Pages').dataTable(
            {
                "ordering": false,
                "paging": true,
                "pagingType": "full_numbers",
                "stateSave": true
            });
    });

    $('#CreateNewsletter').click(function () {

        var selectedLang = $('#LangSelect').val();


        if (selectedLang != "") {
            $('#NullWarning').hide();
            location.href = '@(Url.Action("Create", "Document"))?doctype=newsletter&pageCategory=newsletter&lang=' + selectedLang;
        }
        else {
            $('#NullWarning').show();
        }

    });

</script>