MB9WebCore/MB9WebTemplate/Controllers/FilesController.cs
using ElFinder;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MB9.CMS.Web.Helper
{
    public class FilesController : Controller
    {
        private Connector _connector;

        public Connector Connector
        {
            get
            {
                if (_connector == null)
                {
                    FileSystemDriver driver = new FileSystemDriver();
                    DirectoryInfo thumbsStorage = new DirectoryInfo(Server.MapPath("~/App_Data/images/testThumbs"));
                    //driver.AddRoot(new Root(new DirectoryInfo(@"C:\Program Files"))
                    //{
                    //    IsLocked = true,
                    //    IsReadOnly = true,
                    //    IsShowOnly = true,
                    //    ThumbnailsStorage = thumbsStorage,
                    //    ThumbnailsUrl = VirtualPathUtility.ToAbsolute("~/Thumbnails/")
                    //});
                    driver.AddRoot(new Root(new DirectoryInfo(Server.MapPath("~/Content/resources/images")), VirtualPathUtility.ToAbsolute("~/Content/resources/images/"))
                    {
                        Alias = "images",
                        StartPath = new DirectoryInfo(Server.MapPath("~/Content/resources/images")),
                        ThumbnailsStorage = thumbsStorage,
                        MaxUploadSizeInMb = 2.2,
                        ThumbnailsUrl = VirtualPathUtility.ToAbsolute("~/Thumbnails/")
                    });
                    driver.AddRoot(new Root(new DirectoryInfo(Server.MapPath("~/Content/resources/docs")), VirtualPathUtility.ToAbsolute("~/Content/resources/docs/"))
                    {
                        Alias = "docs",
                        StartPath = new DirectoryInfo(Server.MapPath("~/Content/resources/docs")),
                        ThumbnailsStorage = thumbsStorage,
                        MaxUploadSizeInMb = 2.2,
                        ThumbnailsUrl = VirtualPathUtility.ToAbsolute("~/Thumbnails/")
                    });
                    _connector = new Connector(driver);
                }
                return _connector;
            }
        }
        public ActionResult FilePicker()
        {
            return Connector.Process(this.HttpContext.Request);
        }

        public ActionResult SelectFile(string target)
        {
            return Json(Connector.GetFileByHash(target).FullName);
        }

        public ActionResult FileSelect(string target)
        {
            return Json(Connector.GetFileByHash(target).Name);
        }
        public ActionResult Thumbs(string tmb)
        {
            return Connector.GetThumbnail(Request, Response, tmb);
        }

        public ActionResult ShowPicker()
        {
            return View();
        }

    }
}

MB9WebCore/MB9WebTemplate/Views/Shared/_LoginMaster.cshtml
<html>

<head>
    <title></title>
    <!-- Custom CSS -->
    <link href="~/Content/css/sb-admin-2.css" rel="stylesheet">

    <link href="~/Content/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="~/Content/font-awesome-4.1.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">
</head>

<body>
    <div class="col-lg-8" style="background-image: url(@Url.Content("~/Content/Images/redBubbles.png"));background-size:cover;height:100%;">
        <div style="margin-top:33%;margin-left:11%;width:48%">
            @*<span style="font-size:295%;color:whitesmoke;font-family:Helvetica Neue,Helvetica,Arial,sans-serif">@ViewBag.projecttitle<br /> @ViewBag.tagline</span>*@
            <h1>
                <span style="color:whitesmoke">@ViewBag.projecttitle</span>
                <br /><small> @ViewBag.tagline</small>
            </h1>
        </div>
    </div>

    <div class="col-lg-3" style="width: 25%; margin-top: 10%;">
        @RenderBody()
</div>
    <div class="col-lg-3" style="margin-top: 19%;float:right;">
        <img src="~/Content/Images/inginim-logo-long.png" style="float:right;height: 30px;margin-right: 15%;" />

    </div>


</body>
</html>

MB9WebCore/MB9WebTemplate/Views/Shared/_MainLayout.cshtml
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">


    <!-- Jquery-1.11.0. -->
    <script src="~/Content/js/jquery-1.11.0.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="~/Content/js/bootstrap.min.js"></script>

    <!-- DateTime Picker-->
    <script type="text/javascript" src="@Url.Content("~/Content/Plugins/datetimepicker/jquery.datetimepicker.js")"></script>

    <!-- Metis Menu Plugin JavaScript -->
    <script src="~/Content/js/Plugins/metisMenu/metisMenu.min.js"></script>

    <!-- DataTables -->
    <script type="text/javascript" charset="utf8" src="@Url.Content("~/Content/Plugins/DataTables-1.10.2/js/jquery.dataTables.js")"></script>

    <!-- Mustache -->
    <script src="~/Content/Plugins/Mustache/js/mustache.js"></script>

    <!-- Jquery-UI -->
    <script src="~/Content/Plugins/uibootsrap/jquery-ui.js"></script>

    <!-- Moment JavaScript-->
    <script src="~/Content/Plugins/calendar/moment.min.js"></script>

    <!-- Jquery Calendar-->
    <script src="~/Content/Plugins/calendar/fullcalendar.min.js"></script>

    <!-- Custom Theme JavaScript -->
    <script src="~/Content/js/sb-admin-2.js"></script>
    <script src="@Url.Content("~/Content/cms/cms.js")"></script>

    <!-- El FInder -->
    <script type="text/javascript" src="@Url.Content("~/Content/Plugins/elfinder/js/elfinder.min.2.1.js")"></script>

    <!-- Tiny MCE -->
    <script type="text/javascript" src="@Url.Content("~/Content/Plugins/tinymce/js/tinymce/tinymce.min.js")"></script>
    <script type="text/javascript">
        tinymce.init({
            selector: "textarea.htmleditor",
            menubar: false,
            // statusbar: false,
            file_browser_callback: elFinderBrowser,
            theme: "modern",
            plugins: [
                "advlist autolink lists link charmap",
                "wordcount visualblocks visualchars image code",
                "nonbreaking save contextmenu directionality",
                "textcolor colorpicker textpattern"
            ],
            toolbar1: "insertfile undo redo | styleselect | bold italic | forecolor backcolor | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image | code"
        });

        function elFinderBrowser(field_name, url, type, win) {
            tinymce.activeEditor.windowManager.open({
                file: '@Url.Action("ShowPicker", "Files", new { area="" })',
                title: 'Select Image',
                width: 900,
                height: 450,
                resizable: 'yes'
            }, {
                setUrl: function (url) {
                    win.document.getElementById(field_name).value = url.url;
                }
            });
            return false;
        }
    </script>

    <!-- Bootstrap Treeview -->
    <script type="text/javascript" src="@Url.Content("~/Content/Plugins/treeview/js/bootstrap-treeview.js.min.2.1.js")"></script>

    <script>
        $('#tree').treeview({
            // The naming convention for callback's is to prepend with `on`
            // and capitalize the first letter of the event name
            // e.g. nodeSelected -> onNodeSelected
            onNodeSelected: function (event, data) {
                // Your logic goes here
            }
            });
        
    </script>

    <!-- CSS -->

    <!-- Jquery Ui Bootstrap-->
    <link href="~/Content/Plugins/uibootsrap/jquery-ui-1.10.0.custom.css" rel="stylesheet" />
    <link href="~/Content/Plugins/uibootsrap/jquery.ui.1.10.0.ie.css" rel="stylesheet" />
    @*<link href="~/Content/themes/theme2/css/custom-theme/jquery-ui-1.10.3.custom.css" rel="stylesheet">
    <link href="~/Content/themes/theme2/css/custom-theme/jquery-ui-1.10.3.theme.css" rel="stylesheet">
    <link href="~/Content/themes/theme2/css/custom-theme/jquery.ui.1.10.3.ie.css" rel="stylesheet">*@

    <!-- Bootstrap Core CSS -->
    <link href="~/Content/css/bootstrap.min.css" rel="stylesheet">

    <!-- Bootstrap Date Time Picker-->
    <link rel="stylesheet" type="text/css" media="screen" href="~/Content/Plugins/datetimepicker/jquery.datetimepicker.css" />

    <!-- MetisMenu CSS -->
    <link href="~/Content/css/Plugins/metisMenu/metisMenu.min.css" rel="stylesheet">

    <!-- Data table-->
    <link rel="stylesheet" type="text/css" href="~/Content/Plugins/DataTables-1.10.2/css/jquery.dataTables.css">
    @*<link href="~/Content/css/jquery.dataTables.css" rel="stylesheet">*@

    <!-- JQuery Calendar-->
    <link href="@Url.Content("~/Content/Plugins/calendar/fullcalendar.min.css")" rel="stylesheet" />

    <!-- Custom CSS -->
    <link href="~/Content/css/sb-admin-2.css" rel="stylesheet">

    <!-- Custom MB9 CSS -->
    <link href="~/Content/Site-MB9.css" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="~/Content/font-awesome-4.1.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">

    <!-- ElFinder -->
    <link rel="stylesheet" type="text/css" media="screen" href="~/Content/Plugins/elfinder/css/elfinder.min.2.1.css" />
    @*<link rel="stylesheet" type="text/css" media="screen" href="~/Content/Plugins/elfinder/css/smoothness-1.8.23/jquery-ui-1.8.23.custom.css" />*@



    <title>@ViewBag.Title</title>

</head>


<body>

    <div id="wrapper">



        <!-- Navigation Top bar -->
        @Html.Partial("_TopBar")


        <!--popup-->
        @*@Html.Partial("_Pop_ups")*@

        <!--Menu-->
        @Html.Partial("_SideBarMenu")

        <!-- Page Content -->
        <div id="page-wrapper" style="min-height: 926px;">
            <div class="row">
                <div class="col-lg-12">
                    <h3 class="page-header">
                        @ViewBag.Header<small> @ViewBag.Subheading </small>
                    </h3>
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
            <div class="row">

                <!--Notifications-->
                @*@Html.Partial("_Notifications")*@

    <!--Main body-->
    @RenderBody()

            </div>
            <!-- /#page-wrapper -->
            <!--Page footer-->
            

        </div>
        <!-- /#wrapper -->
    </div>
    @Html.Partial("_PageFooter")
</body>
</html>

MB9WebCore/MB9WebTemplate/Views/Shared/_MainViewLayout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>@ViewBag.Title</title>

    <!-- Bootstrap Core CSS -->
    <link href="~/Content/themes/theme3/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="~/Content/themes/theme3/css/modern-business.css" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="~/Content/themes/theme3/font-awesome-4.1.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https: //oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https: //oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>
    @Scripts.Render("~/bundles/jquery")
    @*@Scripts.Render("~/Scripts/bootstrap.min.js")*@
    @RenderSection("scripts", required: false)

    <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation" style="margin-bottom:20px;">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header" style="float:left;margin-bottom:25px;margin-top:25px;">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" >
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">TMS</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            @*<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">*@
            <div style="float:right;margin-right:1px;position:relative;z-index:300;margin-top:25px;">
                @*@Html.Action("DisplayMenuBar")
                <ul class="nav navbar-nav navbar-right">
                <li>
                    <a href="#">About</a>
                </li>
                <li>
                    <a href="#">Programmes</a>
                </li>

                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Customized Solutions <b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li>
                            <a href="#">Blog Home 1</a>
                        </li>
                        <li>
                            <a href="#">Blog Home 2</a>
                        </li>
                        <li>
                            <a href="#">Blog Post</a>
                        </li>
                    </ul>
                </li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Insights for Leaders <b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li>
                            <a href="#">Full Width Page</a>
                        </li>
                        <li>
                            <a href="#">Sidebar Page</a>
                        </li>
                        <li>
                            <a href="#">FAQ</a>
                        </li>
                        <li class="active">
                            <a href="#">404</a>
                        </li>
                        <li>
                            <a href="#">Pricing Table</a>
                        </li>
                    </ul>
                </li>
                <li>
                    <a href="#">Calendar</a>
                </li>
                <li>
                    <a href="#">Contact Us</a>
                </li>
            </ul>*@
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <!-- Page Content -->
    <div class="container" style="margin-top:20px;">

        <!-- Page Heading/Breadcrumbs -->
        @*<div class="row">
            <div class="col-lg-12">
                <div style="float:left">
                <h1 class="page-header">
                    @ViewBag.Header<small> @ViewBag.Subheading </small>
                </h1>
                    </div>
                @*<div style="float:right;margin-top:50px;margin-right:10px;position:relative;z-index:300">
                    @Html.Action("DisplayMenuBar")
                </div>
                <div style="clear:both"></div>*@
                @*<ol class="breadcrumb">
                <li>
                    <a href="../Index">Home</a>
                </li>
                <li class="active"></li>
            </ol>
        </div>
    </div>*@
        <!-- /.row -->

        <div class="row" style="position:relative; z-index:1;">

            @*<div class="col-lg-12">
                <div class="jumbotron">
                    <h1>
                        
                    </h1>*@
                    @RenderBody()

                @*</div>*@
            </div>

        </div>

        <hr>

        <!-- Footer -->
        <footer>
            <div class="row">
                <div class="col-lg-12">
                    <p>Copyright &copy; Inginim 2017</p>
                </div>
            </div>
        </footer>

    </div>
    <!-- /.container -->

    <!-- Jquery-1.11.0. -->
    <script src="@Url.Content("~/Content/js/jquery-1.11.0.js")"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="@Url.Content("~/Content/js/bootstrap.min.js")"></script>

</body>

</html>

MB9WebCore/MB9WebTemplate/Views/Shared/_Notifications.cshtml
<div id="notify" class="alert-success" style="display:none;text-align:center">
    @{
        string msg = "";
    }
    @if (ViewBag.SuccessMessage != null)
    {
        msg = ViewBag.SuccessMessage;
        ViewBag.SuccessMessage = "";
    }
    <label id="user-notify-lb">@msg</label>
</div>

<div id="errornotify" class="alert-danger" style="display:none;text-align:center">
    @{
        string emsg = "";
    }
    @if (ViewBag.ErrorMessage != null)
    {
        emsg = ViewBag.ErrorMessage;
        ViewBag.ErrorMessage = "";
    }
    <label id="user-errornotify-lb">@emsg</label>
</div>


<script type="text/javascript">

    $(document).ready(function () {
        var value = $('#user-notify-lb').text();
        if (value != "") {
            displaynotification(value);

        }

        var ervalue = $('#user-errornotify-lb').text();
        if (ervalue != "") {
            displayerrornotification(ervalue);

        }

    });

    function displaynotification(text) {
        if (text != null) {
            $('#user-notify-lb').text(text);
            $('#notify').show();
            $('#user-notify-lb').show();
            setTimeout('$("#notify").hide()', 1500);
        }
    }
    function displayerrornotification(text) {
        if (text != null) {
            $('#user-errornotify-lb').text(text);
            $('#errornotify').show();
            $('#user-errornotify-lb').show();
            setTimeout('$("#errornotify").hide()', 1500);

        }
    }



</script>

MB9WebCore/MB9WebTemplate/Views/Shared/_PageFooter.cshtml
<nav class="navbar navbar-default navbar-fixed-bottom" role="navigation" style="margin-bottom: 0; font-weight: bold; min-height: 25px; color: rgb(113, 113, 114);">
    <div style="float: right;">
        Powered by Inginim Pvt Ltd
    </div>
</nav>

MB9WebCore/MB9WebTemplate/Views/Shared/_SideBarMenu.cshtml
@{
    var UserRole = ViewBag.currentUserRole;
    var allRoles = ViewBag.avail_roles;
    bool IsAdmin = ViewBag.IsAdmin;
}


<div class="navbar-default sidebar" role="navigation" style="margin-top:0px">
    <!--.sidebar-collapse -->
    <div class="sidebar-nav navbar-collapse">
        <ul class="nav" id="side-menu">
            @if (UserRole == "DVR" || UserRole == "Both" || UserRole == "Admin")
            {
            <li>
                <a id="menu_blog" class="mainmenu">DVR View</a>
            </li>
            }
            @if (UserRole == "Door" || UserRole == "Both" || UserRole == "Admin")
            {
            <li>
                <a id="menu_blog" class="mainmenu">Door View</a>
            </li>
            }
            @if (UserRole == "Admin" || UserRole == "AdminMember" || IsAdmin == true)
            {
            <li>
                <a id="menu_user" href="#" class="mainmenu"><i class="fa fa-user fa-fw"></i>Admin Settings<span class="fa arrow"></span></a>
                <ul class="nav nav-second-level collapse">
                    <li>
                        <a id="menu_users" class="mainmenu">DVR Configuration</a>
                    </li>
                    <li>
                        <a id="menu_users" class="mainmenu">Door Configuration</a>
                    </li>
                    <li>
                        <a id="menu_users" href="@VirtualPathUtility.ToAbsolute("~/AdminUser/User/List")" class="mainmenu">All Users</a>
                    </li>
                    @*@if (allRoles != null) 
                    { 
                        foreach (var item in allRoles) 
                        {
                        <li>
                            <a id="menu_roles + @item.Value" class="mainmenu" href="@VirtualPathUtility.ToAbsolute("~/AdminUser/User/MemberList")">@item.Text</a>

                        </li>
                        }
                    }*@
                    @*<li>
                        <a id="menu_members" href="@VirtualPathUtility.ToAbsolute("~/AdminUser/User/MemberList")" class="mainmenu">Members</a>
                    </li>*@
                 </ul>
            </li>
            }
            else 
            {
            <li>

            </li>
            }


        </ul>
    </div>
    <!-- /.sidebar-collapse -->
</div>


@*<script>
    $(document).ready(function ()
    {
        $('#menu_user').click()
    });
</script>*@

MB9WebCore/MB9WebTemplate/Views/Shared/_TopBar.cshtml
<nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">BOSCH</a>
    </div>
    <!-- /.navbar-header -->
    
    <ul class="nav navbar-top-links navbar-right">
       
        <li >
            
            welcome @ViewBag.topbar_name
            <!-- /.dropdown-user -->
        </li>
        <!-- /.dropdown -->
        <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                <i class="fa fa-user fa-fw"></i>  <i class="fa fa-caret-down"></i>
            </a>
           
            <ul class="dropdown-menu dropdown-user">

                <li>
                    <a href=@Url.Action("Logout", "Access", new {area="AdminUser" })><i class="fa fa-sign-out fa-fw"></i> Logout</a>
                </li>
            </ul>
            <!-- /.dropdown-user -->
        </li>
        <!-- /.dropdown -->
    </ul>

</nav>